id = "jai"
name = "Jai"
version = "0.0.1"
schema_version = 1
authors = ["Stowy <stowy@protonmail.ch>"]
description = "Jai support."
repository = ""

[grammars.jai]
repository = "https://github.com/St0wy/tree-sitter-jai"
commit = "37475aa813e9a7c55e185be9f2ee01f83cf8e69c"
