id = "jai"
name = "Jai"
version = "0.0.1"
schema_version = 1
authors = ["Stowy <stowy@protonmail.ch>"]
description = "Jai support."
repository = "https://github.com/St0wy/zed-jai"

[grammars.jai]
repository = "https://github.com/St0wy/tree-sitter-jai"
commit = "de182c0db2770c40721bbc84739e05a01b16f36f"
